### ISSUE TITLE
Document.funding element needs to be an array of objects

### ISSUE THREAD

**Issue by seasidesparrow** [adsabs/ingest_data_model#18]
Funding data for records can be fielded by funding agency, the agency's DOI, and the award number among others.  Some records may also have multiple funding agencies/awards.

Document["funding"] is currently a single-valued plain text field, but it should be an array of funding objects, where the funding object includes at a minimum:
- Agency name/acronym
- AgencyID
- Award number

Additional subfields might include a date range for each funding item, and making the AgencyID itself an object with AgencyID having a type (e.g. DOI, ROR), and a value.

**Comment by ehenneken** [comment]
Here's an example of a record with multiple awards: https://api.crossref.org/v1/works/10.3847/2041-8213/acbcc9

The Crossref funding search is a powerful tool to explore the funding landscape: https://search.crossref.org/funding

**Comment by seasidesparrow** [comment]
Fixed by #19
