### ISSUE TITLE
Add enum to keyword keySystem

### ISSUE THREAD

**Issue by mugdhapolimera** [adsabs/ingest_data_model#22]
Need to create list of possible enums for keySystem. There must be an option in the list for UAT.

**Comment by seasidesparrow** [comment]
@csgrant00 do we want to add in other keyword systems like AGU, APS along with UAT, AAS here?

**Comment by mugdhapolimera** [comment]
If it helps, current list of active keywords are ["UAT", "AAS", "misc", "datacite", "subject", "arxiv", "Elsevier"]
